### ISSUE TITLE
joi dependency

### ISSUE THREAD

**Issue by kpturner** [ben-ng/mutex-js#1]
I installed with npm install mutex -save

but it fails to run - unable to find module "joi"

Should this be a dependency rather than a devDependency?

**Comment by ben-ng** [comment]
whoops! you're right. fixing.

**Comment by ben-ng** [comment]
published in 1.0.3. thanks so much.

**Comment by kpturner** [comment]
No prob - great little library btw. Ideal for what I wanted and saved me the hassle of writing it myself 👍

**Comment by ben-ng** [comment]
Let me know if you run into other issues; I just released it last month, so there are bound to be hiccups.
