### ISSUE TITLE
Problem on Centos using node 7.7.3 and redis server 2.4.10 

### ISSUE THREAD

**Issue by kpturner** [ben-ng/mutex-js#3]
I developed an app that uses mutex.js on a windows platform and it all works as expected.  When I deploy the same application on a Centos server running node 7.7.3 and redis server 2.4.10 it fails to obtain a lock.

I have tested simply by running `node test/edge-coverage/redis.js` and this works on Windows but on the Centos server I get `Unhandled rejection Error: Timed out before acquiring the lock` as shown below:
```
TAP version 13
    # Subtest: redis strategy - fails when no options are given
    ok 1 - Should throw if missing options
    1..1
ok 1 - redis strategy - fails when no options are given # time=78.624ms

    # Subtest: redis strategy - fails when server does not exist
    1..1
    ok 1 - Failed with Error: Redis connection to this-be-broken:6379 failed - g   etaddrinfo ENOTFOUND this-be-broken this-be-broken:6379
ok 2 - redis strategy - fails when server does not exist # time=60.964ms

    # Subtest: redis strategy - acquisition times out
Unhandled rejection Error: Timed out before acquiring the lock
    at /usr/sails/projects/mutex/strategies/redis-strategy.js:79:16
    at Timeout.<anonymous> (/usr/sails/projects/mutex/node_modules/async/lib/asy   nc.js:789:30)
    at Timeout._onTimeout (/usr/sails/projects/mutex/node_modules/async/lib/asyn   c.js:167:37)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

**Comment by ben-ng** [comment]
Looks like it can't connect to the redis server. Is the redis server running locally? Try `localhost` instead of `127.0.0.1` or vice-versa.

**Comment by kpturner** [comment]
Yes it is a local server. I agree it seems to be a connection issue but other areas of the app access the same Redis server using other libraries (or just using the raw Redis client) and they all work fine (by host name or ip).

**Comment by ben-ng** [comment]
Since I don't have access to your environment, this sounds like something you'll have to debug yourself, probably by modifying the gaggle module's channel code in your `node_modules` folder.

I developed and tested this module on OS X, and the CI server runs tests in some flavor of Linux, so I can't imagine what the problem is.

I am pleasantly surprised that it works on Windows, though.
